[build]
  publish = "dist"
  command = "npm install && npm run build"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Garantir que as variáveis de ambiente sejam passadas para o build
[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200