[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  # Environment variables are automatically available during build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200